export const BEGIN_AJAX_CALL='BEGIN_AJAX_CALL';
export const LOAD_AUTHORE_SUCCESS='LOAD_AUTHORE_SUCCESS';
export const LOAD_COURSE_SUCCESS='LOAD_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCESS='UPDATE_COURSE_SUCESS';
export const CREATE_COURSE_SUCESS='CREATE_COURSE_SUCESS';
